### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by andres-condezo** [hendridg/clone-youtube#1]
## HI @hendridg 

Good job so far!

## Highlights
- Clean code 🟢 
- Good ux/ui 🟢 

## Suggestion:
- You could use variables for your colors in your CSS file  like your previous projects

![](https://64.media.tumblr.com/5a97be1dba647633e37cce9b571e30d2/tumblr_mnvx967abB1sr1ki0o1_250.gifv) 

Cheers and Happy coding!

**Comment by vanillainanutshell** [comment]
- Nicely made
- I'd recommend you to use linters so your code can have a better identation
- I'd recommend you to make a more descriptive README file

<img src="https://media2.giphy.com/media/l0IyjCRcRa6pQo2S4/giphy.gif"/>

**Comment by eduardosancho** [comment]
![](https://media.giphy.com/media/ABPYR9xUWHPsBH9A6y/giphy.gif)
